### ISSUE TITLE
Errors with newset PHP version

### ISSUE THREAD

**Issue by ymjonline** [Luc45/Very-Simple-Password-for-Wordpress#2]
Hi, great plugin but any plan to update to support PHP 7 that we are all supposed to migrate to ?

It now triggers errors and renders the underlying website/WP unusable.

`Warning: Use of undefined constant timestamp - assumed 'timestamp' (this will throw an Error in a future version of PHP) in [...]/wp-content/plugins/very-simple-password/very-simple-password-for-wordpress.php on line 440`

`...line 471`

`Warning: Cannot modify header information - headers already sent by (output started at /...../wp-content/plugins/very-simple-password/very-simple-password-for-wordpress.php:440) in /........../wp-content/plugins/very-simple-password/very-simple-password-for-wordpress.php on line 478`

thank you

**Comment by Luc45** [comment]
Hi,

Yes, I am working on an update right now that will be compatible with PHP 5.4+.

In the meantime, you can fix it by opening the file wp-content/plugins/very-simple-password/very-simple-password.php and going to line 440, and replacing:

This:
`current_time(timestamp)`

With this:
`current_time('timestamp')`

I forgot the brackets on timestamp. Usually PHP will silently add those for me, but when you have warnings to show up it will throw that warning.

Sorry about that, stay tuned for an update in the coming weeks.

Best,
Lucas

**Comment by ymjonline** [comment]
thanks for the swift reply and workaround.
Was about to check how to fix it by myself but now it's crystal clear
